# -*- coding: utf-8 -*-
"""tugas_23_coding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMK3tY9zryl4PY1IO4U1jwodDJYxAr9J
"""

#import semua library yang kalian butuhkan disini
import json, requests
import json, tweepy

#sel ini digunakan untuk membaca tokens kalian. simpan berkas token.json pada folder yang sama dengan file tugas ini

with open("token.json") as f:
  tokens = json.load(f)

bearer_token = tokens['bearer_token']
api_key = tokens['api_key']
api_key_secret = tokens['api_key_secret']
access_token = tokens['acces_token']
acces_token_secrett = tokens['acces_token_secret']

tokens.keys()

#buat variabel authentikasi dan api
auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token,acces_token_secrett)
api = tweepy.API(auth, wait_on_rate_limit=True)

#Buatlah sebuah fungsi dengan nama user_timeline_scraper()
#fungsi tersebut memiliki input username dari user
#Fungsi ini berguna untuk mengambil 10 tweet yang berada di timeline user.
#gunakan metode Cursor untuk tugas ini
#gunakan tweet_mode --> extended

posts = api.user_timeline(screen_name="MataNajwa", count = 200, lang ="en", tweet_mode="extended")

#username = "MataNajwa"
#user_timeline_scraper(username)
#mencetak 10 berita terakhir
print("Berikut ini adalah 10 twit terakhir dari akun @MataNajwa:\n")
i=1
for tweet in posts[:10]:
    print(str(i) +') '+ tweet.full_text + '\n')
    i= i+1